package com.example.excelForSettlement;
public enum ExpenseType {
    WITHOUTSPLIT,
    SPLITINHALF,
    SPLITINROKSANA,
    FILIPSPECIFICPRICEROKSANAREMAINING,
    ROKSANASPECIFICPRICEFILIPREMAINING,
    FILIPSPLITMORE,
    ROKSANASPLITMORE,
    SPLITSPECIFICEPRICESFILIPFIRST,
    SPLITSPECIFICEPRICESROKSANAFIRST,
    SPLITSPECIFICESINGLEFILIPPRICERESTSPLITINHALF,
    SPLITSPECIFICESINGLEROKSANAPRICERESTSPLITINHALF,
    SPLITSPECIFICEPRICESFILIPFIRSTRESTSPLITINHALF,
    SPLITSPECIFICEPRICESROKSANAFIRSTRESTSPLITINHALF,
    OTHER;
}
